# Generated by Django 5.1 on 2025-04-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('referal_code', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
