# Generated by Django 5.1 on 2025-04-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_users_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='referal_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
