# Generated by Django 5.1 on 2025-04-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_students_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='referal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
