# Generated by Django 5.1 on 2025-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_students_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='user_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
