# Generated by Django 5.1 on 2025-04-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_students_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='referal_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='students',
            name='user_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
