# Generated by Django 5.1 on 2025-04-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_students_referal_code_alter_students_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='referal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
